# Site settings
title: The Incredible Rust
description: >-
  The premier destination for people looking to learn and master the Rust programming language.
  Learn Rust through practical examples and hands-on exercises.
baseurl: ""
url: "https://incrediblerust.github.io"

# Multilingual settings
languages: ["en", "pt", "es"]
default_lang: "en"

# Content collections (used by Rust generator)
collections:
  lessons:
    output: true
    permalink: /:collection/:name/
  lessons_pt:
    output: true
    permalink: /pt/:collection/:name/
  lessons_es:
    output: true
    permalink: /es/:collection/:name/

# Default values for content types
defaults:
  - scope:
      path: ""
      type: "lessons"
    values:
      layout: "lesson"
      lang: "en"
  - scope:
      path: ""
      type: "lessons_pt"
    values:
      layout: "lesson"
      lang: "pt"
  - scope:
      path: ""
      type: "lessons_es"
    values:
      layout: "lesson"
      lang: "es"

# Files to exclude from processing
exclude:
  - src/
  - target/
  - Cargo.toml
  - Cargo.lock
  - build.sh
  - templates/
  - GENERATOR_README.md
  - TAREFAS_MODERNIZACAO_WEB_DESIGN_2025.md
  - node_modules
  - README.md
  - LICENSE

# Site metadata
version: "1.0.0"
rust_version: "1.85.0"
generator: "Custom Rust Static Site Generator"